### ISSUE TITLE
New pegjs version - commit 475215aa523d9fcc0c62b1eda8a4f25155d0b086

### ISSUE THREAD

**Issue by jdmichaud** [pegjs/bower#1]
Hello,
Would it be possible to update the pegjs bower component following the commit 475215aa523d9fcc0c62b1eda8a4f25155d0b086 which expose the visitor API of pegjs ?

Let me know if you need me for any help.

**Comment by michel-kraemer** [comment]
I can create a `development` branch and upload a current snapshot of peg.js there. Then you are able to reference the branch directly in bower. Would that be OK for you?

**Comment by jdmichaud** [comment]
Sure. But why not integrate it in the release first? Is it for testing purposes?

**Comment by michel-kraemer** [comment]
I'm sorry. I thought you wanted to test this feature and have some kind of a snapshot. If you want it to be integrated in the release then please open an issue in the https://github.com/pegjs/pegjs repository and not here. This is just the repository for the bower package and not for peg.js itself.
